# @package _global_

defaults:
  - override /model: classification
  - override /model/network/backbone: openclip_B_32
  - _self_

class_name: 'area'
model:
  optimizer:
    optim:
      lr: 0.0002
      weight_decay: 0.0001

is_baseline: false
max_epochs: 15

dataset:
  global_batch_size: 2048
