# @package _global_

defaults:
  - override /model: regression
  - override /model/network/backbone: clip_L_14_DataComp
  - _self_

model:
  optimizer:
    optim:
      lr: 0.0002
      weight_decay: 0.0001

is_baseline: false
max_epochs: 30

dataset:
  global_batch_size: 2048