# @package _global_

defaults:
  - override /model: hybrid
  - override /model/network/backbone: openclip_B_32
  - override /model/network/mid: mlp_hybrid
  - _self_

class_name: 'quadtree_10_1000'
is_baseline: false
max_epochs: 30

model:
  optimizer:
    optim:
      lr: 0.0002
      weight_decay: 0.0001

dataset:
  global_batch_size: 2048
