defaults:
  - backbone: openclip_B_32
  - mid: mlp
  - head: regression

instance:
  _target_: models.networks.network.ContrastiveFrozenBackbone
  backbone : ${model.network.backbone}
  mid: ${model.network.mid}
  head: ${model.network.head}
  mode: ${mode}

class_name: ${class_name}
