defaults:
  - backbone: openclip_B_32
  - mid: mlp
  - head: regression

instance:
  _target_: models.networks.network.LoraBackbone
  backbone : ${model.network.backbone}
  mid: ${model.network.mid}
  head: ${model.network.head}
  r: ${lora_r}
  alpha: ${lora_alpha}
  dropout: ${lora_dropout}
  bias: ${lora_bias}

class_name: ${class_name}
