defaults:
  - optimizer: adam
  - lr_scheduler: none
  - network: frozen_backbone
  - loss: cls
  - override network/head: classification
  - _self_

name: Classification
aux_data: ${aux_data}
text_tuning: ${text_tuning}
