defaults:
  - optimizer: adam
  - lr_scheduler: none
  - network: text_contrastive
  - text_network: clip
  - loss: text_tuning
  - _self_

name: Regression
aux_data: ${aux_data}
text_tuning: ${text_tuning}
