# @package _global_

defaults:
  - override /model: regression
  - override /model/network: lora_backbone
  - override /model/network/backbone: openclip_B_32
  - _self_

is_baseline: false

lora_r: 32
lora_alpha: 256
lora_dropout: 0.1
lora_bias: lora_only
max_epochs: 30

dataset:
  global_batch_size: 2048
